language: cpp
compiler: g++
sudo: false

cache:
  apt: true
  directories:
    - ${HOME}/cmake_build

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:boost-latest/ppa'
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran
      - python-dev
      - libboost1.55-all-dev
      - libblas-dev
      - liblapack-dev

before_script:
- export CC="gcc-4.9"
- export CXX="g++-4.9"

script:
- cp scripts/build/travis/configure_travis_trusty.sh cmake_build/configure.sh
- cd cmake_build
- bash configure.sh
