language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"

script:
- cp scripts/build/dist/configure_ubuntu_16_04.sh cmake_build/configure.sh
- cd cmake_build
- sh configure.sh
