sudo: false
dist: trusty
language: cpp
compiler: g++

git:
  depth: 3

cache: ccache

env:
  global:
    - CCACHE_COMPILERCHECK=content
    - CCACHE_COMPRESS=true
    - CCACHE_NODISABLE=true
    - CCACHE_MAXSIZE=500M

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:boost-latest/ppa'
    packages:
      - gcc-6
      - g++-6
      - gfortran
      - libboost1.55-dev
      - libboost-serialization1.55-dev
      - libboost-python1.55-dev
      - libblas-dev
      - liblapack-dev

before_script:
- export CC="ccache gcc-6"
- export CXX="ccache g++-6"
- export PYTHONPATH=${PYTHONPATH}:${TRAVIS_BUILD_DIR}
- export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${TRAVIS_BUILD_DIR}/libs

script:
- cp scripts/build/travis/configure_travis_trusty.sh cmake_build/configure.sh
- cd cmake_build
- bash configure.sh
- ccache -s
- cd ../kratos/python_scripts
- python run_tests.py
